# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- name: '旅行 Travel'
  tag: 'travel'
  subitems:
    - name: '前蘇聯國家 Soviet States'
      tag: 'soviet'
- name: '文化 Culture'
  tag: 'culture'
- name: '城市 City'
  tag: 'city'
- name: '關於我們 About'
  tag: 'about'

social:
- icon: 'facebook'
  link: 'https://www.facebook.com/lifetimesojourner'
- icon: 'instagram'
  link: 'https://instagram.com/lifetimesojourner'
- icon: 'medium'
  link: 'https://medium.com/@jeromecyang'
- icon: 'envelope'
  link: 'mailto:hi@jeromeyang.com'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
