# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-2'

menu:
- name: '旅行 Travel'
  tag: 'Travel'
  subitems:
    - name: '中亞 Central Asia'
      tag: 'Central Asia'
    - name: '北非 North Africa'
      tag: 'North Africa'
    - name: '高加索 Caucasus'
      tag: 'Caucasus'
    - name: '東歐 Eastern Europe'
      tag: 'Eastern Europe'
    - name: '西歐 Western Europe'
      tag: 'Western Europe'
    - name: '北美 North America'
      tag: 'North America'
    - name: '前蘇聯國家 Soviet States'
      tag: 'Soviet'
    - name: '穆斯林國家 Muslim States'
      tag: 'Muslim'
    - name: '大旅行 Grand Trip 2018'
      tag: 'Grand Trip'
- name: '跨文化 Cross-Culture'
  tag: 'Cross-Culture'
- name: '波士頓 Boston'
  tag: 'Boston'
#- name: '關於我 About'
#  tag: 'About'

social:
- icon: 'facebook'
  link: 'https://www.facebook.com/lifetimesojourner'
- icon: 'instagram'
  link: 'https://instagram.com/lifetimesojourner'
- icon: 'medium'
  link: 'https://medium.com/@jeromecyang'
- icon: 'envelope'
  link: 'mailto:hi@jeromeyang.com'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
